### ISSUE TITLE
OnChain NFT Images

### ISSUE THREAD

**Issue by ryjin111** [thirdweb-example/marketplace-template#15]
Images from OnChain NFTs are not displaying

**Comment by kien-ngo** [comment]
Hey there, your on-chain NFT collection (as we have discussed before), has a metadata format that does not match our conventional NFT metadata. For example:

We are looking for:
```typescript
{
  image: "data:image/svg+xml;base64,..."
}
```

You NFT collection:

```typescript
{
  image_data: "data:image/svg+xml;base64,..."
}
```

An effective workaround is to add an extra logic around the <MediaRenderer />:
```jsx
const isOnchain: boolean = ...; 
...
{isOnChain ? 
  <MediaRenderer src={item.metadata['image_data'] .../> : 
  <MediaRenderer src={item.metadata.image} ... />
}
```

**Comment by ryjin111** [comment]
@kien-ngo 
just changing image to image_data works even though there's a error things are working fine
src={nft?.metadata.image_data}

**Comment by kien-ngo** [comment]
Hey! Can you share the error message?

**Comment by ryjin111** [comment]
> Hey! Can you share the error message?

![image](https://github.com/thirdweb-example/marketplace-template/assets/81433235/85fd2580-d062-4fb6-91b8-7c2434fb05a6)
It's working on local dev but uploading to vercel is not

**Comment by ryjin111** [comment]
More errors detailed 
![image](https://github.com/thirdweb-example/marketplace-template/assets/81433235/69aa342d-f643-4294-bde4-1e79ab720acb)

**Comment by kien-ngo** [comment]
It's coming from TypeScript and not the template. Basically you can do:
```
item.metadata.image_data as string ?? ""
```

**Comment by ryjin111** [comment]
> It's coming from TypeScript and not the template. Basically you can do:
> 
> ```ts
> item.metadata.image_data as string ?? ""
> ```

Awesome it's working now 

is my logical expression usage correct?
![image](https://github.com/thirdweb-example/marketplace-template/assets/81433235/0a5816b5-9f5c-481e-823a-c0ac4aaa4c92)

**Comment by ryjin111** [comment]
yoo @kien-ngo update it's working now just need to put away the `cosnst isOnchain: Boolean and the logical expression`

**Comment by ryjin111** [comment]
@kien-ngo does the creator fee is automatically included on the selling transaction?

**Comment by kien-ngo** [comment]
Are you talking about the fees setup for the marketplace contract? You should do that in the thirdweb Dashboard

**Comment by ryjin111** [comment]
> Are you talking about the fees setup for the marketplace contract? You should do that in the thirdweb Dashboard

When i do the setup 

It only uses 1 address on platform fees

Is there way to enable the creator fees?
